server:
  port: 8787
  context-path: /microservice-example2 #  pom中的finalName
  tomcat:
      uri-encoding: UTF-8

spring:
  application:
    name: microservice-example2
  jackson:
    serialization:
      indent_output: true

#eureka
eureka:
  instance:
    hostname: localhost
    port: 8181
    statusPageUrlPath: ${server.context-path}/info
    healthCheckUrlPath: ${server.context-path}/health
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 10 #eureka client发送心跳给server端的频率（默认30秒）
    lease-expiration-duration-in-seconds: 20 #eureka client发送心跳给server端后，续约到期时间（默认90秒）
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/microservice-eureka/eureka/
    registry-fetch-interval-seconds: 10 #eureka client间隔多久去拉取服务注册信息（默认30秒）对于api-gateway如果要迅速获取服务注册状态，可以缩小该值
#log
logging:
  config: classpath:logback-spring.xml

