server:
  port: 8389

spring:
  application:
    name: microservice-elasticsearch
  data:
    elasticsearch:
      cluster-name: testEs # elasticsearch集群名称，默认的是elasticsearch
      cluster-nodes: 10.10.10.10:9300  #节点的地址 注意api模式下端口号是9300，千万不要写成9200

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10 #eureka client发送心跳给server端的频率（默认30秒）
    lease-expiration-duration-in-seconds: 20 #eureka client发送心跳给server端后，续约到期时间（默认90秒）
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8181/microservice-eureka/eureka/

logging:
  config: classpath:logback-spring.xml

management:
  health:
    elasticsearch:
      enabled: false #关闭ES的健康检查
