server:
  port: 8080
  context-path: /microservice-zuul #  pom中的finalName

spring:
  application:
    name: microservice-zuul
  #redis
  redis:
    host: 10.83.36.115
    port: 6379
    password: oamRedis

#用户登录token保持时长（秒）.
user:
  token:
    keep-time: 60000

#eureka
eureka:
  instance:
    hostname: localhost
    port: 8181
    statusPageUrlPath: ${server.context-path}/info
    healthCheckUrlPath: ${server.context-path}/health
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 10 #续约更新频率，默认是30s
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/microservice-eureka/eureka/
    registry-fetch-interval-seconds: 10 #拉取服务注册时间，默认60，改小实现发布后尽快访问
#log
logging:
  config: classpath:logback-spring.xml

#zuul会统一过滤会话(AccessSessionFilter),这里设置不过滤的地址，并且在拦截器中加以判断
zuul:
  sensitiveHeaders:
  ignore:
    url:
      login: /authentication/login
      # 文件上传由于content-type 是multipart/form-data，无法从request中获取参数，故在组件内自行校验
      fileUpload: /file/fileUpload
  #开启重试
  retryable: true
  #设置zuul的信号量隔离，这个在压测的时候会体现出来，zuul会控制单个接口信号量，默认超过100就返回500
  semaphore:
    max-semaphores: 1000

#单个请求时长，默认是1000ms，太短
hystrix:
  command:
    #    针对单个服务设置熔断时间
    microservice-mybatis-plus:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 100000
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 3000

#服务下线后，zuul重试
ribbon:
  OkToRetryOnAllOperations: true #是否所有操作都重试，若false则仅get请求重试
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他实例最大重试次数,不含首次实例
  MaxAutoRetries: 0   #(同一实例最大重试次数,不含首次调用)
  retryableStatusCodes: 404,500,503
    #  这里需要结合hystrix时长配置，例如熔断时间是10s，这里是1s，则熔断时间无效
    ConnectTimeout: 120000
    ReadTimeout: 120000
